[project]
name = "pytorch-ppo"
version = "0.1.0"
description = "Simple PPO implementation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[atari]>=1.1.1",
    "numpy>=2.2.5",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "wandb>=0.19.10",
]
